name = "landing-page-1906"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[vars]
# Add your environment variables here or in the Dashboard
# RESEND_API_KEY = "re_..."
# CONTACT_EMAIL = "..."
# TURNSTILE_SECRET_KEY = "..."
