name = "landing-page-1906"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your environment variables here or in the Dashboard
# RESEND_API_KEY = "re_..."
# CONTACT_EMAIL = "..."
# TURNSTILE_SECRET_KEY = "..."
